export const Config = {
  CACHE_TTL_MS: 10 * 60 * 1000, // 10 minutes
  MAX_CITIES: 5,
  FETCH_INTERVAL_MS: 15 * 60 * 1000, // 15 minutes (iOS minimum)
  BACKGROUND_TASK_NAME: 'WEATHER_BACKGROUND_FETCH',
  SEARCH_DEBOUNCE_MS: 300,
  FETCH_STAGGER_MS: 200,
  HOURLY_DISPLAY_COUNT: 8,
  FORECAST_DAYS: 7,
  DEFAULT_DND_START: 22, // 10 PM
  DEFAULT_DND_END: 7,    // 7 AM
  RAIN_SENSITIVITY_DEFAULT: 40, // %
  UV_WARNING_THRESHOLD: 6,
  TEMP_LOW_THRESHOLD: 0,   // Celsius
  TEMP_HIGH_THRESHOLD: 30, // Celsius
} as const;
